# Generated by Django 4.1.7 on 2024-08-30 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0123_chapter_last_update_chapter_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='qr_code',
            field=models.ImageField(default='blank-lecture.jpeg', upload_to='qr-codes'),
        ),
    ]
