# Generated by Django 4.1.7 on 2024-09-05 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0125_chaptermember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapterlecture',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='chapterlecture',
            name='image',
        ),
        migrations.RemoveField(
            model_name='chapterlecture',
            name='teacher_img',
        ),
        migrations.RemoveField(
            model_name='chapterlecture',
            name='teacher_name',
        ),
        migrations.RemoveField(
            model_name='chapterlecture',
            name='title',
        ),
        migrations.AddField(
            model_name='chapterlecture',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
