# Generated by Django 4.1.7 on 2024-09-05 17:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0126_remove_chapterlecture_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapterlecture',
            name='added_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
