# Generated by Django 4.1.7 on 2024-09-05 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0127_chapterlecture_added_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='buychapter',
            name='chapter_value',
            field=models.IntegerField(blank=True, default='0'),
        ),
        migrations.AddField(
            model_name='buychapter',
            name='link',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='buychapter',
            name='serial',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='buychapter',
            name='method',
            field=models.CharField(blank=True, choices=[('wallet', 'Wallet'), ('chapter_code', 'Chapter Code'), ('admin', 'Admin'), ('link', 'Link')], default='wallet', max_length=25),
        ),
    ]
