# Generated by Django 4.1.7 on 2024-09-05 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0128_buychapter_chapter_value_buychapter_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaptermember',
            name='method',
            field=models.CharField(blank=True, choices=[('wallet', 'Wallet'), ('admin', 'Admin'), ('code', 'Code'), ('qr_code', 'Qr Code'), ('link', 'Link'), ('request', 'Request')], default='admin', max_length=25),
        ),
    ]
