# Generated by Django 4.1.7 on 2024-09-05 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0130_transaction_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='item_type',
            field=models.CharField(blank=True, choices=[('lecture', 'Lecture'), ('chapter', 'Chapter')], default='lecture', max_length=25, null=True),
        ),
    ]
