# Generated by Django 4.1.7 on 2024-09-05 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0132_alter_buychapter_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaptermember',
            name='method',
            field=models.CharField(blank=True, choices=[('wallet', 'Wallet'), ('admin', 'Admin'), ('code', 'Code'), ('qr_code', 'Qr Code'), ('link', 'Link')], default='admin', max_length=25),
        ),
    ]
