# Generated by Django 4.1.7 on 2024-09-05 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0134_studentquestion_lecture_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentquestion',
            name='question_image',
            field=models.ImageField(blank=True, null=True, upload_to='student_question_images'),
        ),
        migrations.AddField(
            model_name='studentquestionanswer',
            name='answer_image',
            field=models.ImageField(blank=True, null=True, upload_to='student_question_answer_images'),
        ),
    ]
