# Generated by Django 4.1.7 on 2024-09-06 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0135_studentquestion_question_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentquestionanswer',
            name='answer_record',
            field=models.FileField(blank=True, upload_to='answers-records'),
        ),
    ]
