# Generated by Django 4.1.7 on 2024-09-06 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0136_studentquestionanswer_answer_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='leaderboard',
            field=models.BooleanField(default=False),
        ),
    ]
