# Generated by Django 4.1.7 on 2024-09-06 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0137_platformsettings_leaderboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformsettings',
            name='website_title',
            field=models.CharField(blank=True, default='Teacher Name', max_length=100, null=True),
        ),
    ]
