# Generated by Django 4.1.7 on 2024-09-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0138_alter_platformsettings_website_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='true_answers',
            field=models.IntegerField(default=0),
        ),
    ]
