# Generated by Django 4.1.7 on 2024-09-12 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0140_part_custom_player_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='part',
            old_name='custom_player_url',
            new_name='custom_youtube_url',
        ),
    ]
