# Generated by Django 4.1.7 on 2024-10-26 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0141_rename_custom_player_url_part_custom_youtube_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='corrected',
            field=models.BooleanField(default=False),
        ),
    ]
