# Generated by Django 4.1.7 on 2024-10-26 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0142_answer_corrected'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='teacher_comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
