# Generated by Django 4.1.7 on 2025-01-02 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0144_alter_answer_teacher_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentopen',
            name='isShuffled',
            field=models.BooleanField(default=False),
        ),
    ]
