# Generated by Django 4.1.7 on 2025-01-02 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0145_assignmentopen_isshuffled'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='virtual_number',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
