# Generated by Django 4.1.7 on 2025-01-02 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0146_answer_virtual_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='shuffleQuestions',
            field=models.BooleanField(default=False),
        ),
    ]
