# Generated by Django 4.1.7 on 2025-01-03 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0148_rename_isshuffled_assignmentopen_altershuffle'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='bunnyCDN',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
